### PR TITLE
Add helm charts

### PR DESCRIPTION
**Pull request by kolima**

### CODE REVIEW

**Comment by belopash** [comment]
Hello, can you please update README.md with instructions on how user can run archives with helm?

**Comment by kolima** [comment]
> Hello, can you please update README.md with instructions on how user can run archives with helm?

Done

**Comment by mo4islona** [comment]
Hi there! Great job so far!

But I have some suggestion / requirements

1) We should avoid duplicate `typesBundle.json` Could your just create symlinks?  Will it works?
2) Indexer should be a `StatefullSet` instead of `Deployment`, because only one concurrent indexer is allowed at any time 
3) There is a some bug with namespace

```
➜  chart git:(feature/helm) ✗ helm install squid -n bitfrost   --create-namespace .
NAME: squid
LAST DEPLOYED: Tue Mar 22 13:45:58 2022
NAMESPACE: bitfrost
STATUS: deployed
REVISION: 1
TEST SUITE: None

➜  chart git:(feature/helm) ✗ helm install squid2 -n bitfrost2   --create-namespace .
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: IngressClass "nginx" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "squid2": current value is "squid"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "bitfrost2": current value is "bitfrost"
```
I guess we dont need a complete installation of  `https://kubernetes.github.io/ingress-nginx` — only a ingress resource with configurable class appropriate to installed ingress controller in a cluster.
```
indexerGateway:
  ingress: 
    enabled: true
    ingressClassName: 'nginx'
  ```

4) Could you make components optional like this?

```yaml
db:
  enabled: false
  image: postgres:12
indexer:
  image: subsquid/hydra-indexer:5
  env: 
     name: POSTGRES_PASSWORD # env form secret should be also supported
     value: <<SECRET>>
  postgres: # posgres is installed outside this helm chart
     url: postgres
     user: postgres 
     port: 25432 # custom port
  redis: # redis is also installed outside this helm
     url: redis
     port: 25432 # custom port
     db: 0
redis:
  enabled: false     
  ```
 
Maybe is better to generate somehow these chart directories for each archive?

**Comment by kolima** [comment]
> Hi there! Great job so far!
> 
> But I have some suggestion / requirements
> 
> 1. We should avoid duplicate `typesBundle.json` Could your just create symlinks?  Will it works?
> 2. Indexer should be a `StatefullSet` instead of `Deployment`, because only one concurrent indexer is allowed at any time
> 3. There is a some bug with namespace
> 
> ```
> ➜  chart git:(feature/helm) ✗ helm install squid -n bitfrost   --create-namespace .
> NAME: squid
> LAST DEPLOYED: Tue Mar 22 13:45:58 2022
> NAMESPACE: bitfrost
> STATUS: deployed
> REVISION: 1
> TEST SUITE: None
> 
> ➜  chart git:(feature/helm) ✗ helm install squid2 -n bitfrost2   --create-namespace .
> Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: IngressClass "nginx" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "squid2": current value is "squid"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "bitfrost2": current value is "bitfrost"
> ```
> 
> I guess we dont need to fully installation of `https://kubernetes.github.io/ingress-nginx` — only a ingress resource itself.
> 
> ```
> indexerGateway:
>   ingress: 
>     enabled: true
>     ingressClassName: 'nginx'
> ```
> 
> 4. Could you make components optional like this?
> 
> ```yaml
> db:
>   enabled: false
>   image: postgres:12
> indexer:
>   image: subsquid/hydra-indexer:5
>   env: 
>      name: POSTGRES_PASSWORD # env form secret should be also supported
>      value: <<SECRET>>
>   postgres: # posgres is installed outside this helm chart
>      url: postgres
>      user: postgres 
>      port: 25432 # custom port
>   redis: # redis is also installed outside this helm
>      url: redis
>      port: 25432 # custom port
>      db: 0
> redis:
>   enabled: false     
> ```
> 
> Maybe is better to generate somehow these chart directories for each archive?

Good, I will check each item. We can try to create a global chart and subcharts, which will only contain values for different projects which we will use in the global chart, and we will not duplicate the core of chart

**Comment by kolima** [comment]
@belopash Done

**Comment by kolima** [comment]
@mo4islona Done

**Pull request merged**
